marca: selector_check_379
marca.com: selector_check_536
el pais: selector_check_170
el mundo: selector_check_163
sport: selector_check_964
sport.es: selector_check_914
as: selector_check_22
as.com: selector_check_915
la vanguardia: selector_check_371
abc: selector_check_4
abc.es: selector_check_436
eldiario.es: selector_check_876
