atletismo femenino: "\"atletismo femenino\""
baloncesto femenino: "\"baloncesto femenino\""
balonmano femenino: "\"balonmano femenino\""
ciclismo femenino: "\"ciclismo femenino\""
escalada mujer: "\"escalada femenina\" OR \"Silvia Vidal\""
futbol femenino: "\"futbol femenino\""
golf femenino: "\"golf femenino\""
hipica mujer: "\"hipica femenina\" OR \"Paola Amilibia\""
judo femenino: "\"judo femenino\" OR \"María Bernabéu\""
montaña mujer: "\"montaña mujer\""
natacion femenina: "\"natacion femenina\" OR \"Mireia Belmonte\""
padel femenino: "\"padel femenino\""
tenis femenino: "\"tenis femenino\" OR \"Conchita Martínez\""
voleibol femenino: "\"voleibol femenino\""

